trigger:
  - main

resources:
  - repo: self

variables:
  vmImage: 'ubuntu-latest'  # Use a valid agent image

stages:
  - stage: Build
    displayName: Build Node Application
    jobs:
      - job: Build
        displayName: Build Node Application
        pool:
          vmImage: $(vmImage)
        steps:
          # Checkout code
          - checkout: self

          # Set up Node.js environment
          - task: NodeTool@0
            displayName: Set up Node.js
            inputs:
              versionSpec: '16.x'  # Adjust to your Node.js version

          # Install dependencies
          - script: |
              npm install
            displayName: Install Dependencies

          # Build the application
          - script: |
              npm run build
            displayName: Build Application

          # Publish artifact
          - task: PublishBuildArtifacts@1
            displayName: Publish Build Artifact
            inputs:
              pathToPublish: $(System.DefaultWorkingDirectory)/dist  # Adjust to your build output directory
              artifactName: node-app
              publishLocation: Container

  - stage: Test
    displayName: Run Tests
    dependsOn: Build
    jobs:
      - job: Test
        displayName: Run Application Tests
        pool:
          vmImage: $(vmImage)
        steps:
          # Checkout code
          - checkout: self

          # Set up Node.js environment
          - task: NodeTool@0
            displayName: Set up Node.js
            inputs:
              versionSpec: '16.x'  # Adjust to your Node.js version

          # Install dependencies
          - script: |
              npm install
            displayName: Install Dependencies

          # Run tests
          - script: |
              npm test
            displayName: Run Tests
