trigger:
  - main

resources:
  - repo: self

variables:
  vmImage: 'ubuntu-latest'
  dockerHubServiceConnection: 'dockerConnection'
  imageName: 'samtec7856/gello'
  buildArtifactName: 'application-artifact'

stages:
  # Stage 1: Build the application and publish an artifact
  - stage: Build
    displayName: Build and Publish Artifact
    jobs:
      - job: Build
        displayName: Build and Publish Artifact
        pool:
          vmImage: $(vmImage)
        steps:
          - checkout: self

          - task: NodeTool@0
            displayName: Set up Node.js
            inputs:
              versionSpec: '18.x'

          - script: |
              node -v
              npm -v
            displayName: Verify Node.js Version

          - script: |
              npm install
            displayName: Install Dependencies

          - script: |
              npm run build
            displayName: Build Application

          # Publish Build Artifact
          - task: PublishBuildArtifacts@1
            displayName: Publish Build Artifact
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/dist'  # Ensure this is the correct output path
              ArtifactName: 'application-artifact'
              publishLocation: 'Container'

  # Stage 2: Build and Push Docker Image
  - stage: Docker
    displayName: Build and Push Docker Image
    dependsOn: Build
    jobs:
      - job: BuildAndPush
        displayName: Build and Push Docker Image
        pool:
          vmImage: $(vmImage)
        steps:
          - checkout: self

          - task: Docker@2
            displayName: Log in to Docker Hub
            inputs:
              command: login
              containerRegistry: $(dockerHubServiceConnection)

          - task: Docker@2
            displayName: Build Docker Image
            inputs:
              command: build
              Dockerfile: ./Dockerfile
              tags: |
                $(imageName):$(Build.BuildId)
                $(imageName):latest

          - script: |
              docker images
            displayName: Verify Docker Image

          - task: Docker@2
            displayName: Push Docker Image
            inputs:
              containerRegistry: $(dockerHubServiceConnection)
              repository: $(imageName)
              command: push
              tags: |
                $(Build.BuildId)

  # Stage 3: Publish Artifact for Release Pipeline
  - stage: PublishArtifact
    displayName: Drop Artifact for Release
    dependsOn: Build
    jobs:
      - job: DropArtifact
        displayName: Drop Artifact
        pool:
          vmImage: $(vmImage)
        steps:
          - task: DownloadPipelineArtifact@2
            displayName: Download Build Artifact
            inputs:
              artifactName: 'application-artifact'

          - task: PublishBuildArtifacts@1
            displayName: Drop Artifact for Release
            inputs:
              pathToPublish: '$(System.DefaultWorkingDirectory)'
              artifactName: 'release-artifact'
              publishLocation: Container
