name: Build and deploy Angular app to GitHub Pages - gello

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies and build Angular app
        run: |
          npm install --legacy-peer-deps
          npm run build -- --configuration=production --output-path=dist/gello --base-href=/gello/ --deploy-url=/

      - name: Verify build output
        run: ls -R dist/gello  # Ensure the build output is in dist/gello

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: gello
          path: dist/gello  # Upload the correct folder

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: gello

      - name: Verify artifact content
        run: ls -R

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist/gello  # Point to the correct folder



# name: Build and deploy Angular app to Azure Web App - e-kart

# on:
#   push:
#     branches:
#       - none
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4

#       - name: Set up Node.js version
#         uses: actions/setup-node@v3
#         with:
#           node-version: '18.x'

#       - name: npm install, build, and test
#         run: |
#           npm install --legacy-peer-deps
#           npm run build -- --configuration=production --base-href=/ --deploy-url=/

#       - name: Zip artifact for deployment
#         run: zip -r release.zip ./dist/*

#       - name: Upload artifact for deployment job
#         uses: actions/upload-artifact@v3
#         with:
#           name: e-kart
#           path: release.zip

#   deploy:
#     runs-on: ubuntu-latest
#     needs: build
#     environment:
#       name: 'Production'
#       url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

#     steps:
#       - name: Download artifact from build job
#         uses: actions/download-artifact@v3
#         with:
#           name: e-kart

#       - name: Unzip artifact for deployment
#         run: unzip release.zip
        
#       - name: 'Deploy to Azure Web App'
#         id: deploy-to-webapp
#         uses: azure/webapps-deploy@v2
#         with:
#           app-name: 'e-kart'
#           slot-name: 'production'  # Ensure this matches your Azure configuration
#           publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_1E1344FA4B9A4C4DBB51C960EC92287A }}
#           package: .
